### ISSUE TITLE
Display formating needed

### ISSUE THREAD

**Issue by probablyalright** [R-Krumins/Python-PW4-Group08-#1]
https://github.com/R-Krumins/Python-PW4-Group08-/blob/30d43b414d51073f3b7ae2b39e72ea778b38b90a/task2.py#L34-L36
Output needs to be formatted so that all numbers align in a straight vertical line, example:
````
SORTED:
   caret.cam.ac.uk: 1 *
         gmail.com: 1 *
         iupui.edu: 8 ********
media.berkeley.edu: 4 ****
         uct.ac.za: 6 ******
         umich.edu: 7 *******
````
